version: '2'

services:
    data:
        image: tianon/true
        volumes:
            - $VOLDIR:/config

    nzbget:
        image: adamant/nzbget
        depends_on:
            - data
        volumes_from:
            - data
            - container:media
        restart: always
        ports:
            - "6789:6789"

    deluge:
        image: adamant/deluge
        depends_on:
            - data
        volumes_from:
            - data
            - container:media
        restart: always
        ports:
            - "8112:8112"
            - "58846:58846"
            - "53160:53160"
            - "53160:53160/udp"

    sickrage:
        image: adamant/sickrage
        depends_on:
             - deluge
             - nzbget
        volumes_from:
            - data
            - container:media
        restart: always
        ports:
            - "8081:8081"

    couchpotato:
        image: adamant/couchpotato
        depends_on:
             - deluge
             - nzbget
        volumes_from:
            - data
            - container:media
        restart: always
        ports:
            - "5050:5050"

    plex:
        image: adamant/alpine-plex
        depends_on:
            - sickrage
            - couchpotato
        volumes_from:
            - data
            - container:media
        restart: always
        network_mode: "host"
        ports:
            - "32400:32400"

    plexpy:
        image: adamant/plexpy
        depends_on:
            - plex
        volumes_from:
            - data
        restart: always
        ports:
            - "8182:8181"
