version: '2'

services:
    data:
        image: tianon/true
        volumes:
            - $VOLDIR:/config

    nzbget:
        image: adamant/nzbget
        depends_on:
            - data
        volumes_from:
            - data
            - container:media
        restart: always

    deluge:
        image: adamant/deluge
        depends_on:
            - data
        volumes_from:
            - data
            - container:media
        restart: always

    sickrage:
        image: adamant/sickrage
        depends_on:
             - deluge
             - nzbget
        volumes_from:
            - data
            - container:media
        restart: always

    couchpotato:
        image: adamant/couchpotato
        depends_on:
             - deluge
             - nzbget
        volumes_from:
            - data
            - container:media
        restart: always

    headphones:
        image: adamant/headphones
        depends_on:
             - deluge
             - nzbget
        volumes_from:
            - data
            - container:media
        restart: always

    plex:
        image: adamant/alpine-plex
        depends_on:
            - sickrage
            - couchpotato
            - headphones
        volumes_from:
            - data
            - container:media
        restart: always
        network_mode: "host"
        ports:
            - "32400:32400"

    plexpy:
        image: adamant/plexpy
        depends_on:
            - plex
        volumes_from:
            - data
        restart: always
    
    web:
        image: nginx:alpine
        volumes:
            - $VOLDIR/launcher/nginx.cfg:/etc/nginx/conf.d/media.conf
        restart: always
        ports:
            - "80:80"
