version: '2'

services:
    data:
        image: tianon/true
        volumes:
            - $VOLDIR:/config

    nzbget:
        image: adamant/nzbget
        depends_on:
            - data
        volumes_from:
            - data
            - container:media
        restart: always

    deluge:
        image: adamant/deluge
        depends_on:
            - data
        volumes_from:
            - data
            - container:media
        restart: always

    sickrage:
        image: adamant/sickrage
        depends_on:
             - deluge
             - nzbget
        volumes_from:
            - data
            - container:media
        restart: always

    couchpotato:
        image: adamant/couchpotato
        depends_on:
             - deluge
             - nzbget
        volumes_from:
            - data
            - container:media
        restart: always

    plex:
        image: adamant/alpine-plex
        depends_on:
            - sickrage
            - couchpotato
        volumes_from:
            - data
            - container:media
        restart: always
        ports:
            - "1900:1900/udp"
            - "3005:3005"
            - "5353:5353/udp"
            - "8324:8324"
            - "32400:32400"
            - "32410:32410/udp"
            - "32412-32414:32412-32414/udp"
            - "32469:32469"

    plexpy:
        image: adamant/plexpy
        depends_on:
            - plex
        volumes_from:
            - data
        restart: always
    
    web:
        image: nginx:alpine
        volumes:
            - $VOLDIR/nginx/nginx.cfg:/etc/nginx/conf.d/media.conf
            - $VOLDIR/nginx/Muximux:/www
        restart: always
        ports:
            - "80:80"
        depends_on:
            - plexpy

    php:
        image: php:fpm-alpine
        working_dir: /www
        volumes:
            - $VOLDIR/nginx/Muximux:/www

