version: '2'

services:
    nzbget:
        image: adamant/nzbget
        volumes:
            - $VOLDIR/nzbget:/config
        volumes_from:
            - container:media
        restart: always

    deluge:
        image: adamant/deluge
        volumes:
            - $VOLDIR/deluge:/config
        volumes_from:
            - container:media
        restart: always

    hydra:
        image: adamant/nzbhydra
        volumes:
            - $VOLDIR/hydra:/config
        restart: always

    sickrage:
        image: adamant/sickrage
        depends_on:
             - deluge
             - nzbget
        volumes:
            - $VOLDIR/sickrage:/config
        volumes_from:
            - container:media
        restart: always

    radarr:
        image: adamant/radarr
        depends_on:
             - deluge
             - nzbget
        volumes:
            - $VOLDIR/radarr:/config
        volumes_from:
            - container:media
        restart: always

    plex:
        image: adamant/plexmediaserver:plexpass
        depends_on:
            - sickrage
            - radarr
        volumes:
            - $VOLDIR/plex:/config/Plex Media Server
        volumes_from:
            - container:media
        restart: always
        ports:
            - "1900:1900/udp"
            - "3005:3005"
            - "5353:5353/udp"
            - "8324:8324"
            - "32400:32400"
            - "32410:32410/udp"
            - "32412-32414:32412-32414/udp"
            - "32469:32469"

    plexpy:
        image: adamant/plexpy
        depends_on:
            - plex
        volumes:
            - $VOLDIR/plexpy:/config
        restart: always
    
    web:
        image: nginx:alpine
        volumes:
            - $VOLDIR/nginx/nginx.cfg:/etc/nginx/conf.d/media.conf
            - $VOLDIR/nginx/Organizr:/www
        restart: always
        ports:
            - "80:80"
        depends_on:
            - plexpy

    php:
        image: php:7.0-fpm-alpine
        working_dir: /www
        volumes:
            - $VOLDIR/nginx/Organizr:/www

